services:
  robo-atualizacao-fornecedores:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: robo-atualizacao-fornecedores
    restart: unless-stopped
    volumes:
      - ./data:/app/data
    #   - ${DOCKER_VOLUME_DATABASE}:/app/database
    env_file:
      - .env
