from enum import Enum

class PorteEnum(Enum):
    EIRELI = "EMPRESA INDIVIDUAL DE RESPONSABILIDADE LIMITADA"
    EP = "EMPRESA PUBLICA"
    EPP = "EMPRESA DE PEQUENO PORTE"
    ME = "MICRO EMPRESA"
    MEI = "MICROEMPREENDEDOR INDIVIDUAL"
    N = "NORMAL"
    PF = "PESSOA FISICA"
    SFL = "SEM FINS LUCRATIVOS"
    D = "DEMAIS"


